import type { ProfileId, Quiz } from "../data/types";
import type { MissionDefinition } from "./missionTypes";
type Question = [
  prompt: string,
  art: string,
  options: string[],
  answer: string,
  explanation: string,
];
function mission(
  id: string,
  title: string,
  npcId: string,
  areaId: string,
  prerequisites: string[],
  count: number,
  description: string,
  objectiveLabel: string,
  delisha: Question,
  dinar: Question,
  badge: string,
  stars = 8,
): MissionDefinition {
  const quiz = Object.fromEntries(
    (["delisha", "dinar"] as ProfileId[]).map((profile) => {
      const q = profile === "delisha" ? delisha : dinar;
      return [
        profile,
        {
          id,
          title,
          prompt: q[0],
          illustration: q[1],
          options: q[2],
          answer: q[3],
          explanation: q[4],
        },
      ];
    }),
  ) as Record<ProfileId, Quiz>;
  return {
    id,
    mapId: id.startsWith("k-") ? "krakatau" : "raja-ampat",
    title,
    npcId,
    areaId,
    prerequisites,
    objectives: Array.from({ length: count }, (_, i) => `${id}-${i + 1}`),
    description,
    objectiveLabel,
    reward: { stars, badge },
    quiz,
  };
}
export const MISSIONS: MissionDefinition[] = [
  mission(
    "k-observe",
    "Mata Penjelajah",
    "k-ranger",
    "hill",
    ["welcome"],
    3,
    "Naik bukit dan amati tiga tanda alam.",
    "Pengamatan",
    [
      "Mana yang terlihat di langit?",
      "☁️ 🐦",
      ["Awan", "Kerang", "Kepiting"],
      "Awan",
      "Awan ada di langit. Kita mengamati bentuknya dari tempat aman.",
    ],
    [
      "Mengapa kita mengamati Krakatau dari menara di pulau ini?",
      "🔭 🌋",
      [
        "Untuk menjaga jarak aman",
        "Agar bisa menyentuh lava",
        "Untuk menghalangi burung",
      ],
      "Untuk menjaga jarak aman",
      "Mengamati dari jauh membantu kita belajar sambil tetap aman.",
    ],
    "Pengamat Alam",
  ),
  mission(
    "k-clean",
    "Teluk Tanpa Sampah",
    "k-coast",
    "bay",
    ["welcome"],
    3,
    "Kumpulkan tiga sampah di teluk.",
    "Sampah",
    [
      "Botol plastik bekas sebaiknya kita taruh di mana?",
      "🧴",
      ["Tempat sampah terpilah", "Laut", "Sarang burung"],
      "Tempat sampah terpilah",
      "Pilah sampah bersama orang dewasa agar pantai tetap bersih.",
    ],
    [
      "Manakah sampah anorganik yang kamu temukan?",
      "🧴 🍂",
      ["Botol plastik", "Daun kering", "Kulit buah"],
      "Botol plastik",
      "Plastik sulit terurai. Daun dan kulit buah termasuk sampah organik.",
    ],
    "Sahabat Pesisir",
  ),
  mission(
    "k-volcano",
    "Cerita Gunung Api",
    "k-geologist",
    "trail",
    ["science"],
    3,
    "Baca tiga papan pengetahuan di jalur aman.",
    "Papan",
    [
      "Apa yang keluar perlahan dari kawah pada pulau kita?",
      "🌋",
      ["Asap kecil", "Ikan", "Daun"],
      "Asap kecil",
      "Kawah tampak mengeluarkan asap kecil. Kita melihatnya dari kejauhan.",
    ],
    [
      "Lava yang mendingin dapat menjadi…",
      "🌋 → 🪨",
      ["Batuan", "Plastik", "Kertas"],
      "Batuan",
      "Lava mendingin dan membeku menjadi batuan. Kita mengenalnya lewat papan edukasi.",
    ],
    "Ahli Batuan",
  ),
  mission(
    "ra-clean",
    "Selamatkan Pantai",
    "ra-teacher",
    "ra-beach",
    [],
    3,
    "Cari tiga sampah di Pantai Bersih lalu pelajari cara memilahnya.",
    "Sampah",
    [
      "Botol yang kamu temukan berwarna biru. Bentuk badannya seperti…",
      "🧴",
      ["Tabung", "Bola", "Segitiga"],
      "Tabung",
      "Badan botol berbentuk seperti tabung. Setelah dipakai, botol masuk tempat sampah terpilah.",
    ],
    [
      "Sampah mana yang termasuk organik?",
      "🍂 🧴",
      ["Daun kering", "Botol plastik", "Bungkus plastik"],
      "Daun kering",
      "Daun berasal dari tumbuhan dan dapat terurai. Botol dan bungkus plastik termasuk anorganik.",
    ],
    "Pantai Bersih",
  ),
  mission(
    "ra-animals",
    "Cari Hewan Mangrove",
    "ra-ranger",
    "ra-mangrove",
    ["ra-clean"],
    3,
    "Amati kepiting, burung kuntul, dan ikan gelodok dari jalur kayu.",
    "Hewan",
    [
      "Gambar mana yang menunjukkan kepiting?",
      "🌳",
      ["🦀 Kepiting", "🐈 Kucing", "🦋 Kupu-kupu"],
      "🦀 Kepiting",
      "Kepiting memiliki capit dan dapat hidup di sekitar akar mangrove.",
    ],
    [
      "“Ikan gelodok bergerak di lumpur sekitar akar bakau.” Habitat yang tepat adalah…",
      "🌳 🐟",
      ["Hutan mangrove", "Gurun pasir", "Kamar tidur"],
      "Hutan mangrove",
      "Mangrove menyediakan lumpur, air, dan tempat berlindung bagi ikan gelodok.",
    ],
    "Sahabat Bakau",
  ),
  mission(
    "ra-fish",
    "Hitung Ikan",
    "ra-diver",
    "ra-reef",
    ["ra-clean"],
    1,
    "Amati satu kelompok berisi lima ikan dari jalur kaca.",
    "Kelompok ikan",
    [
      "Berapa ikan pada kelompok yang kamu amati?",
      "🐟 🐟 🐟 🐟 🐟",
      ["3", "5", "7"],
      "5",
      "Hitung satu per satu. Ada lima ikan dengan warna berbeda.",
    ],
    [
      "Ada 5 ikan. Tiga datang, lalu 2 pergi. Berapa yang tersisa?",
      "5 + 3 − 2",
      ["4", "6", "8"],
      "6",
      "5 + 3 = 8. Lalu 8 − 2 = 6 ikan.",
    ],
    "Sahabat Ikan",
  ),
  mission(
    "ra-coral",
    "Jaga Terumbu Karang",
    "ra-diver",
    "ra-reef",
    ["ra-fish"],
    3,
    "Amati tiga bentuk karang tanpa menyentuhnya.",
    "Karang",
    [
      "Ikan kuning cocok dengan warna apa?",
      "🐠",
      ["🟨 Kuning", "🟦 Biru", "🟥 Merah"],
      "🟨 Kuning",
      "Ikan kuning cocok dengan kotak kuning. Karang adalah rumah bagi banyak ikan.",
    ],
    [
      "Mengapa kita tidak boleh menginjak karang?",
      "🪸 🐠",
      [
        "Karang hidup dan menjadi rumah ikan",
        "Karang adalah mainan",
        "Agar karang berubah warna",
      ],
      "Karang hidup dan menjadi rumah ikan",
      "Karang hidup dan tumbuh perlahan. Menginjaknya dapat merusak rumah hewan laut.",
    ],
    "Sahabat Karang",
  ),
  mission(
    "ra-water",
    "Sampel Air",
    "ra-scientist",
    "ra-lab",
    ["ra-animals", "ra-coral"],
    3,
    "Ambil sampel A, B, dan C, lalu bandingkan tampilannya.",
    "Sampel",
    [
      "Sampel mana yang terlihat jernih dan tidak bersampah?",
      "A 🟤   B 💧   C 🗑️",
      ["Sampel A", "Sampel B", "Sampel C"],
      "Sampel B",
      "Sampel B tampak jernih. Namun air jernih belum tentu aman diminum; perlu pemeriksaan.",
    ],
    [
      "A keruh, B jernih, C bersampah. Pilih sampel yang tampak paling bersih.",
      "A 🟤   B 💧   C 🗑️",
      ["Sampel B", "Sampel A", "Sampel C"],
      "Sampel B",
      "B tampak paling bersih. Kejernihan tidak membuktikan air aman diminum. Peneliti masih perlu mengujinya.",
    ],
    "Peneliti Air",
  ),
  mission(
    "ra-guardian",
    "Penjaga Laut",
    "ra-teacher",
    "ra-village",
    ["ra-clean", "ra-animals", "ra-fish", "ra-coral", "ra-water"],
    1,
    "Kunjungi papan janji dan gabungkan semua pengetahuanmu.",
    "Janji",
    [
      "Mana pilihan sahabat laut?",
      "🌊 🐟 🌱",
      [
        "Buang sampah di tempatnya dan sayangi hewan",
        "Buang botol ke laut",
        "Petik semua karang",
      ],
      "Buang sampah di tempatnya dan sayangi hewan",
      "Pantai bersih dan hewan yang terlindungi membuat laut menjadi tempat hidup yang baik.",
    ],
    [
      "Pilih rencana yang menjaga ekosistem pesisir.",
      "🌊 🌳 🪸",
      [
        "Pilah sampah, rawat bakau, amati karang tanpa menyentuh",
        "Tebang bakau dan injak karang",
        "Buang sampah ke air jernih",
      ],
      "Pilah sampah, rawat bakau, amati karang tanpa menyentuh",
      "Kebersihan air, mangrove, dan terumbu saling berkaitan. Kamu sudah menjadi Penjaga Laut!",
    ],
    "Penjaga Laut",
    15,
  ),
  mission(
    "ra-plant",
    "Tiga Bibit untuk Pesisir",
    "ra-ranger",
    "ra-mangrove",
    ["ra-animals"],
    3,
    "Tanam bibit pada tiga petak di tepi jalur kayu.",
    "Bibit ditanam",
    [
      "Berapa bibit yang sudah kamu tanam?",
      "🌱 🌱 🌱",
      ["2", "3", "5"],
      "3",
      "Satu, dua, tiga. Tiga bibit akan tumbuh jika dirawat.",
    ],
    [
      "Kamu menanam 3 bibit. Teman menanam 4. Berapa semuanya?",
      "3 + 4",
      ["6", "7", "8"],
      "7",
      "3 + 4 = 7 bibit. Mangrove membantu melindungi pesisir.",
    ],
    "Penanam Bakau",
  ),
  mission(
    "ra-birds",
    "Sahabat Pulau Burung",
    "ra-birder",
    "ra-birds",
    ["ra-animals"],
    3,
    "Gunakan teropong untuk mengamati tiga burung tanpa mendekati sarang.",
    "Burung",
    [
      "Cocokkan gambar burung dengan kelompok hewannya.",
      "🐦",
      ["Burung", "Ikan", "Kepiting"],
      "Burung",
      "Burung memiliki paruh dan sayap. Ada tiga burung yang kamu amati.",
    ],
    [
      "Mengapa pengamat menjaga jarak dari sarang?",
      "🐦 🪺",
      [
        "Agar burung tidak terganggu",
        "Agar bisa mengambil telur",
        "Agar sarang kosong",
      ],
      "Agar burung tidak terganggu",
      "Sarang adalah tempat burung merawat telur dan anaknya. Amati dari jauh.",
    ],
    "Pengamat Burung",
  ),
  mission(
    "ra-cave",
    "Pola Kristal Rahasia",
    "ra-guide",
    "ra-cave",
    ["ra-coral"],
    3,
    "Cari tiga kristal terang dan pecahkan pola pada papan gua.",
    "Kristal",
    [
      "Bentuk kristal runcing mirip dengan…",
      "🔺",
      ["Segitiga", "Lingkaran", "Bola"],
      "Segitiga",
      "Segitiga memiliki tiga sisi. Kristal pada gua permainan memiliki ujung runcing.",
    ],
    [
      "Pola kristal: 2, 4, 6, … Angka berikutnya?",
      "◇ ◇◇ ◇◇◇",
      ["7", "8", "10"],
      "8",
      "Setiap langkah bertambah dua. 6 + 2 = 8. Sebagian pulau karang memiliki batu kapur.",
    ],
    "Penjelajah Kristal",
  ),
];
export const MISSION_BY_ID = Object.fromEntries(MISSIONS.map((m) => [m.id, m]));
