import type { WorldObject } from "../../data/types";
import {
  area,
  path,
  objects,
  npc,
  scatterTrees,
  directionSigns,
} from "../factories";
import { EXPANDED_RADIUS, type MapDefinition } from "../mapTypes";
const areas = [
  area(
    "ra-village",
    "Desa Pesisir",
    [0, 4],
    "⌂",
    "#e1b67c",
    "Bertemu sahabat laut dan mulai petualangan.",
    8,
  ),
  area(
    "ra-beach",
    "Pantai Bersih",
    [12, 17],
    "♧",
    "#d7c57c",
    "Pilah sampah dan biarkan pantai bersih.",
    9,
  ),
  area(
    "ra-reef",
    "Terumbu Karang",
    [25, 11],
    "◈",
    "#6dbcc2",
    "Lihat ikan melalui jalur snorkeling yang aman.",
    9,
  ),
  area(
    "ra-mangrove",
    "Hutan Mangrove",
    [-24, -12],
    "♣",
    "#68a58c",
    "Cari hewan dan tanam bibit di jalur kayu.",
    10,
  ),
  area(
    "ra-lab",
    "Laboratorium Laut",
    [-6, -23],
    "⚗",
    "#9baad0",
    "Amati sampel air bersama peneliti.",
    8,
  ),
  area(
    "ra-birds",
    "Pulau Burung",
    [21, -25],
    "⌕",
    "#b8b77c",
    "Amati burung dan sarang dari kejauhan.",
    8,
  ),
  area(
    "ra-cave",
    "Gua Rahasia",
    [-23, 22],
    "◇",
    "#b4a4c7",
    "Kristal, pola, dan cerita batuan pulau.",
    8,
  ),
];
const questObjects: WorldObject[] = [
  ...objects(
    "ra-clean",
    "trash",
    ["Botol biru berbentuk tabung", "Daun kering", "Bungkus plastik"],
    [
      [8, 14],
      [13, 18],
      [18, 13],
    ],
  ),
  ...objects(
    "ra-animals",
    "crab",
    ["Kepiting bakau", "Burung kuntul", "Ikan gelodok"],
    [
      [-24, -9],
      [-29, -14],
      [-21, -16],
    ],
    true,
  ).map((o, i) => ({ ...o, visual: (["crab", "bird", "fish"] as const)[i] })),
  ...objects("ra-fish", "fish", ["Kelompok lima ikan"], [[22, 7]], true),
  ...objects(
    "ra-coral",
    "coral",
    ["Karang bercabang", "Karang kipas", "Karang bulat"],
    [
      [25, 10],
      [29, 13],
      [24, 16],
    ],
    true,
  ),
  ...objects(
    "ra-water",
    "sample",
    ["Sampel A · keruh", "Sampel B · jernih", "Sampel C · bersampah"],
    [
      [-8, -24],
      [-3, -27],
      [1, -24],
    ],
  ),
  ...objects("ra-guardian", "observe", ["Janji sahabat laut"], [[3, 4]], true),
  ...objects(
    "ra-plant",
    "plant",
    ["Tanam bibit pertama", "Tanam bibit kedua", "Tanam bibit ketiga"],
    [
      [-26, -4],
      [-30, -7],
      [-31, -11],
    ],
    true,
  ),
  ...objects(
    "ra-birds",
    "bird",
    ["Burung di dahan", "Burung di batu", "Burung dekat sarang"],
    [
      [20, -25],
      [25, -24],
      [19, -29],
    ],
    true,
  ),
  ...objects(
    "ra-cave",
    "crystal",
    ["Kristal pertama", "Kristal kedua", "Kristal ketiga"],
    [
      [-22, 23],
      [-24, 19],
      [-24, 25],
    ],
  ),
];
const interactives: WorldObject[] = [
  npc(
    "ra-teacher",
    "Bu Guru Bahari",
    [0, 3],
    "Selamat datang di Laut Raja Ampat Pintar! Kita belajar menjaga pantai dan semua sahabat laut.",
  ),
  npc(
    "ra-ranger",
    "Kak Bakau",
    [-21, -5],
    "Akar mangrove melindungi pesisir. Cari hewan dari jalur kayu, lalu tanam bibit bersama.",
    2,
  ),
  npc(
    "ra-diver",
    "Kak Nila",
    [20, 3],
    "Lihat ikan dan karang dari jalur kaca. Kita tidak perlu berenang di laut dalam.",
    0,
  ),
  npc(
    "ra-scientist",
    "Bu Dr. Laut",
    [-8, -20],
    "Warna air bisa memberi petunjuk, tetapi air jernih belum tentu aman diminum.",
  ),
  npc(
    "ra-birder",
    "Kak Sayap",
    [16, -21],
    "Gunakan teropong. Jaga jarak dari burung dan sarangnya.",
    2,
  ),
  npc(
    "ra-guide",
    "Pak Kristal",
    [-16, 19],
    "Gua ini terang dan aman. Amati pola kristal sambil mengenal batuan pulau.",
    0,
  ),
  ...questObjects,
  {
    id: "ra-board",
    name: "Papan misi Raja Ampat",
    kind: "board",
    position: [-3, 9],
  },
  ...directionSigns(areas, "ra"),
  ...[
    [-28, 22],
    [26, 18],
    [24, -27],
  ].map((position, i) => ({
    id: `ra-bonus-${i}`,
    name: "Bintang laut tersembunyi",
    kind: "bonus" as const,
    position: position as [number, number],
  })),
];
const trees = scatterTrees(
  areas.filter((a) => a.id !== "ra-reef" && a.id !== "ra-lab"),
  381,
  46,
  interactives,
  EXPANDED_RADIUS,
);
const knowledge: Record<string, string> = {
  "ra-animals-1":
    "Kepiting bakau memiliki capit. Akar mangrove menyediakan tempat berlindung bagi hewan kecil.",
  "ra-animals-2":
    "Burung kuntul mencari makanan di perairan dangkal. Amati paruh, sayap, dan kakinya tanpa mengejar.",
  "ra-animals-3":
    "Ikan gelodok dapat bergerak di lumpur sekitar akar bakau. Mangrove adalah habitatnya.",
  "ra-guardian-1":
    "Janji sahabat laut: memilah sampah, merawat bakau, menjaga air bersih, serta mengamati hewan dan karang tanpa merusaknya.",
  "ra-birds-1":
    "Dari teropong, kita melihat burung di dahan. Tandai satu burung tanpa mengganggunya.",
  "ra-birds-2":
    "Burung kedua beristirahat di batu. Hitung dua burung yang sudah kamu amati.",
  "ra-birds-3":
    "Burung ketiga berada dekat sarang. Kita menjaga jarak; telur dan anak burung perlu dilindungi.",
};
export const rajaAmpatData: MapDefinition = {
  id: "raja-ampat",
  name: "Laut Raja Ampat Pintar",
  description: "Tujuh tempat istimewa, satu janji untuk menjaga laut.",
  theme: "#5caebd",
  radius: EXPANDED_RADIUS,
  spawn: [0, 11],
  ground: () => 0,
  areas,
  objects: interactives.map((o) => ({
    ...o,
    description: knowledge[o.id] || o.description,
  })),
  trees,
  obstacles: [
    { position: [-5, 0], radius: 2.4, height: 4 },
    { position: [5, -2], radius: 2.4, height: 4 },
    { position: [-7, -27], radius: 2.4, height: 4 },
    ...trees.map((t) => ({ position: t.position, radius: 0.42, height: 4 })),
  ],
  paths: [
    path([0, 11], [12, 17]),
    path([0, 5], [20, 3], "wood"),
    path([20, 3], [22, 7], "glass", 4),
    path([22, 7], [29, 13], "glass", 4),
    path([29, 13], [24, 16], "glass", 4),
    path([24, 16], [18, 13], "glass", 4),
    path([0, 4], [-21, -5], "wood"),
    path([-21, -5], [-29, -14], "wood"),
    path([-29, -14], [-21, -16], "wood"),
    path([-21, -16], [-21, -5], "wood"),
    path([0, -7], [-8, -20], "wood"),
    path([-8, -20], [16, -21], "wood"),
    path([16, -21], [21, -25], "wood"),
    path([20, 3], [16, -21], "wood"),
    path([0, 11], [-16, 19], "wood"),
    path([-16, 19], [-24, 25]),
    path([-21, -5], [-16, 19], "wood"),
    path([-8, -20], [-21, -16], "wood"),
  ],
  landmarks: [
    {
      id: "ra-home-1",
      name: "Rumah Pesisir",
      kind: "house",
      position: [-5, 0],
      color: "#dda079",
    },
    {
      id: "ra-home-2",
      name: "Rumah Bahari",
      kind: "house",
      position: [5, -2],
      color: "#72aaa8",
    },
    {
      id: "ra-laboratory",
      name: "Laboratorium Laut",
      kind: "lab",
      position: [-7, -27],
      color: "#859eb9",
    },
    {
      id: "ra-watch",
      name: "Menara Burung",
      kind: "tower",
      position: [21, -25],
    },
    {
      id: "ra-cavern",
      name: "Gua Kristal Ceria",
      kind: "cave",
      position: [-24, 22],
    },
    { id: "ra-pier", name: "Dermaga Pesisir", kind: "dock", position: [2, 19] },
  ],
  missionIds: [
    "ra-clean",
    "ra-animals",
    "ra-fish",
    "ra-coral",
    "ra-water",
    "ra-guardian",
    "ra-plant",
    "ra-birds",
    "ra-cave",
  ],
};
